
package bankingClient;
public enum AccountType{
    ROZLICZENIOWY,
    LOKAT_TERMINOWYCH,
    OSZCZEDNOSCIOWY,
    OSZCZEDNOSCIOWO_ROZLICZENIOWY,
    LOKAT_TERMINOWYCH_OSZCZEDNOSCIOWYCH,
    POWIERNICZY;
}